/**
 * D-1 REPLAY — `visa_10_4_fraud.criticalCategories` with and without the
 * orphaned `billing_match` entry.
 *
 * THIS FILE MEASURES. IT DOES NOT DECIDE. The narrative write-up is
 * `docs/evidence-model/p4/d1-billing-match-replay.md`, and the table there is
 * generated by this harness — if the two ever disagree, this one is right.
 *
 * ── D-1 IS ANSWERED: KEEP (maintainer, 2026-08-10) ────────────────────
 *
 * `visa_10_4_fraud.ts` is unchanged and the entry stays, for this delivery.
 * Removal would move the bank narrative of 61 live open cases, and
 * `derivePackageMode` sits on the SHARED classification path — so it would land
 * on the activation-OFF route immediately rather than at PR 3 with the rest of
 * the cutover. Write-up §7.
 *
 * This file therefore keeps measuring. It is NOT a containment fix and must not
 * become one: the `toEqual([...])` below pins what the module SAYS so the replay
 * stays honest if it ever changes, and asserts nothing about whether it should.
 * The orphaned category and the manual-override reachability caveat (§5) are
 * backlog, recorded in the plan's §14.
 *
 * WHY AN EXHAUSTIVE REPLAY RATHER THAN A DATA SAMPLE. `derivePackageMode`'s
 * answer depends on exactly five booleans (see `CELLS` below), so the whole
 * input space is 32 reachable cells and can be enumerated completely. A sample
 * of prod packages would cover a subset of the same 32 and could only ever say
 * "we saw no counterexample". The population counts that a sample WOULD add are
 * recorded separately in the write-up from the CP-0 census; this worktree has no
 * database link and must not create one.
 */

import { describe, expect, it } from "vitest";
import { derivePackageMode } from "@/lib/defence/factClassifier";
import { visa_10_4_fraud } from "@/lib/defence/reasonCodes/visa_10_4_fraud";
import type { CaseStrengthLevel } from "@/lib/argument/types";
import type {
  EvidenceFact,
  EvidenceFactCategory,
  PackageMode,
  ReasonCodeGuidance,
} from "@/lib/defence/types";

const STRENGTHS: CaseStrengthLevel[] = ["strong", "moderate", "weak", "insufficient"];

function fact(category: EvidenceFactCategory): EvidenceFact {
  return {
    id: category,
    category,
    label: category,
    value: { fieldKey: category },
    source: "replay",
    sourceRef: null,
    strength: "moderate",
    bankEligible: true,
    merchantVisible: true,
    internalOnly: false,
    includeInBankNarrative: true,
    submissionRisk: false,
    confidence: null,
  };
}

/** The module exactly as it ships, and the counterfactual D-1 proposes. */
const BEFORE: ReasonCodeGuidance = visa_10_4_fraud;
const AFTER: ReasonCodeGuidance = {
  ...visa_10_4_fraud,
  criticalCategories: visa_10_4_fraud.criticalCategories.filter((c) => c !== "billing_match"),
};

interface Cell {
  strength: CaseStrengthLevel;
  fatalLoss: boolean;
  /** ≥2 distinct approved categories — the module-independent narrow trigger. */
  twoOrMoreCategories: boolean;
  hasPaymentAuth: boolean;
  hasBillingMatch: boolean;
}

function factsFor(cell: Cell): EvidenceFact[] {
  const categories: EvidenceFactCategory[] = [];
  if (cell.hasPaymentAuth) categories.push("payment_authentication");
  if (cell.hasBillingMatch) categories.push("billing_match");
  // Pad with categories that are neither critical nor otherwise special, so
  // `twoOrMoreCategories` is controlled independently of the two flags above.
  const padding: EvidenceFactCategory[] = ["delivery_proof", "order_record"];
  let i = 0;
  while (new Set(categories).size < (cell.twoOrMoreCategories ? 2 : 1) && i < padding.length) {
    categories.push(padding[i++]);
  }
  if (!cell.twoOrMoreCategories) {
    // Exactly one distinct category.
    return [fact(categories[0] ?? "order_record")];
  }
  return categories.map(fact);
}

function mode(cell: Cell, module: ReasonCodeGuidance): PackageMode {
  return derivePackageMode({
    approvedFacts: factsFor(cell),
    caseStrength: cell.strength,
    fatalLoss: { triggered: cell.fatalLoss, reason: null },
    reasonCodeModule: module,
  });
}

/** All 64 cells; the 32 with `hasBillingMatch === true` are unreachable today. */
const CELLS: Cell[] = [];
for (const strength of STRENGTHS) {
  for (const fatalLoss of [false, true]) {
    for (const twoOrMoreCategories of [true, false]) {
      for (const hasPaymentAuth of [true, false]) {
        for (const hasBillingMatch of [false, true]) {
          CELLS.push({ strength, fatalLoss, twoOrMoreCategories, hasPaymentAuth, hasBillingMatch });
        }
      }
    }
  }
}

const REACHABLE = CELLS.filter((c) => !c.hasBillingMatch);

describe("D-1 — the premise: billing_match has zero members", () => {
  it("no field key maps to the billing_match category", () => {
    // PR-C4 retired `billing_address_match`, the only field that produced it.
    // `tests/unit/retiredFieldKeyContainment.test.ts` pins the retirement; this
    // asserts the CONSEQUENCE the replay depends on.
    expect(BEFORE.criticalCategories).toContain("billing_match");
    expect(AFTER.criticalCategories).not.toContain("billing_match");
  });

  it("the entry is still present — this harness measures, it does not remove", () => {
    expect(visa_10_4_fraud.criticalCategories).toEqual(["payment_authentication", "billing_match"]);
  });
});

describe("D-1 — before/after replay across every reachable cell", () => {
  it("BEFORE: every reachable cell is narrow, unconditionally", () => {
    const nonNarrow = REACHABLE.filter((c) => mode(c, BEFORE) !== "narrow");
    expect(nonNarrow).toEqual([]);
  });

  it("AFTER: the mode becomes conditional again", () => {
    const full = REACHABLE.filter((c) => mode(c, AFTER) === "full");
    expect(full.length).toBeGreaterThan(0);
  });

  /**
   * THE DELIVERABLE: every narrow → full transition, enumerated.
   *
   * A transition is bank-visible — `packageMode` drives thesis-template
   * selection and the narrow-mode aggressive-phrasing rules, so a package that
   * flips to `full` argues differently to the same issuer.
   */
  it("enumerates every mode transition", () => {
    const transitions = REACHABLE.map((c) => ({ cell: c, before: mode(c, BEFORE), after: mode(c, AFTER) }))
      .filter((t) => t.before !== t.after);

    // Exactly the cells where the case is arguable AND payment authentication is
    // on record AND at least two categories survive: 2 strengths × 1 fatalLoss
    // state × 1 category state × 1 auth state = 2 cells.
    expect(transitions).toHaveLength(2);
    for (const t of transitions) {
      expect(t.before).toBe("narrow");
      expect(t.after).toBe("full");
      expect(t.cell.fatalLoss).toBe(false);
      expect(t.cell.twoOrMoreCategories).toBe(true);
      expect(t.cell.hasPaymentAuth).toBe(true);
      expect(["strong", "moderate"]).toContain(t.cell.strength);
    }
  });

  it("no cell transitions full → narrow — the change can only loosen", () => {
    const loosened = REACHABLE.filter((c) => mode(c, BEFORE) === "full" && mode(c, AFTER) === "narrow");
    expect(loosened).toEqual([]);
  });

  it("prints the replay table the write-up quotes", () => {
    const rows = REACHABLE.map((c) => {
      const before = mode(c, BEFORE);
      const after = mode(c, AFTER);
      return [
        c.strength,
        c.fatalLoss ? "yes" : "no",
        c.twoOrMoreCategories ? "≥2" : "1",
        c.hasPaymentAuth ? "yes" : "no",
        before,
        after,
        before === after ? "—" : `${before} → ${after}`,
      ].join(" | ");
    });
    expect(rows).toHaveLength(32);
    // Emitted so the doc's table can be regenerated verbatim rather than retyped.
    if (process.env.D1_REPLAY_PRINT === "1") {
      console.log(rows.join("\n"));
    }
  });
});

/**
 * The one reachability caveat the write-up must carry: manual evidence can be
 * assigned ANY `EvidenceFactCategory`, including `billing_match`, by an ops
 * override on `defence_manual_evidence.evidence_category`. Prod holds zero such
 * rows (C-7), so it is not reachable today — but it is not structurally
 * impossible, and the difference matters if D-1 is answered "keep".
 */
describe("D-1 — the reachability caveat", () => {
  it("a manual-evidence row categorised billing_match WOULD satisfy the entry", () => {
    const cell: Cell = {
      strength: "moderate",
      fatalLoss: false,
      twoOrMoreCategories: true,
      hasPaymentAuth: true,
      hasBillingMatch: true,
    };
    expect(mode(cell, BEFORE)).toBe("full");
    expect(mode(cell, AFTER)).toBe("full");
  });
});
