/**
 * Single-attachment PDF document — one per native `*File` slot
 * populated via the conditional file evidence layer (Phase 3).
 *
 * Layout: header strip + meta block + reason block + content block.
 * Content varies per `attachmentType` but the surrounding chrome is
 * identical so issuers and merchants see a coherent style across slots.
 */
import React from "react";
import { Document, Page, Text, View } from "@react-pdf/renderer";
import { styles } from "./styles";
import type { AttachmentType } from "@/lib/shopify/decideFileAttachments";

export interface EvidenceAttachmentPdfFact {
  label: string;
  value: string;
}

export interface EvidenceAttachmentPdfData {
  attachmentType: AttachmentType;
  evidenceFieldKey: string;
  /** Title shown in the header strip. Mapped from `attachmentType` by
   *  `generateEvidenceAttachmentPdf`. */
  title: string;
  /** Merchant-facing label for the underlying evidence item. */
  label: string | null;
  /** Human-readable string from `decideFileAttachments` — explains why
   *  this file is included; printed in the reason block so the issuer
   *  immediately understands the document's relevance. */
  reason: string;
  /** Shop-facing context. Both purely informational here. */
  shopDomain: string;
  disputeId: string;
  generatedAtIso: string;
  /** Extracted facts (per attachment type). Each row renders as a
   *  key/value pair under "Evidence summary". Empty list is allowed —
   *  the section is suppressed. */
  facts: EvidenceAttachmentPdfFact[];
  /** Optional free-text body (policy excerpts, message bodies, etc.).
   *  Renders below `facts` under "Details". Trimmed to ~2000 chars to
   *  keep the document single-page. */
  body?: string | null;
}

function formatDate(iso: string): string {
  try {
    return new Date(iso).toLocaleString("en-US", {
      month: "short",
      day: "numeric",
      year: "numeric",
      hour: "2-digit",
      minute: "2-digit",
      timeZone: "UTC",
      timeZoneName: "short",
    });
  } catch {
    return iso;
  }
}

function truncate(s: string, max: number): string {
  if (s.length <= max) return s;
  return s.slice(0, max) + " […truncated]";
}

export function EvidenceAttachmentDocument({ data }: { data: EvidenceAttachmentPdfData }) {
  return (
    <Document>
      <Page size="LETTER" style={styles.page}>
        {/* Header strip — title only; no logo placeholder until brand
            assets ship. */}
        <View>
          <Text style={styles.coverTitle}>{data.title}</Text>
          <Text style={styles.coverSubtitle}>DisputeDesk evidence attachment</Text>
        </View>

        {/* Meta block */}
        <View style={{ marginTop: 12, marginBottom: 12 }}>
          <View style={styles.kvRow}>
            <Text style={styles.kvLabel}>Shop</Text>
            <Text style={styles.kvValue}>{data.shopDomain}</Text>
          </View>
          <View style={styles.kvRow}>
            <Text style={styles.kvLabel}>Dispute</Text>
            <Text style={styles.kvValue}>{data.disputeId}</Text>
          </View>
          <View style={styles.kvRow}>
            <Text style={styles.kvLabel}>Evidence field</Text>
            <Text style={styles.kvValue}>{data.evidenceFieldKey}</Text>
          </View>
          {data.label ? (
            <View style={styles.kvRow}>
              <Text style={styles.kvLabel}>Merchant label</Text>
              <Text style={styles.kvValue}>{data.label}</Text>
            </View>
          ) : null}
          <View style={styles.kvRow}>
            <Text style={styles.kvLabel}>Generated</Text>
            <Text style={styles.kvValue}>{formatDate(data.generatedAtIso)}</Text>
          </View>
        </View>

        {/* Reason — why this file is included */}
        <Text style={styles.sectionTitle}>Reason for inclusion</Text>
        <Text style={styles.text}>{data.reason}</Text>

        {/* Per-type facts */}
        {data.facts.length > 0 ? (
          <>
            <Text style={styles.sectionTitle}>Evidence summary</Text>
            {data.facts.map((f, i) => (
              <View style={styles.kvRow} key={`${f.label}-${i}`}>
                <Text style={styles.kvLabel}>{f.label}</Text>
                <Text style={styles.kvValue}>{f.value}</Text>
              </View>
            ))}
          </>
        ) : null}

        {/* Optional body block */}
        {data.body && data.body.trim().length > 0 ? (
          <>
            <Text style={styles.sectionTitle}>Details</Text>
            <Text style={styles.text}>{truncate(data.body.trim(), 2000)}</Text>
          </>
        ) : null}

        <View style={styles.footer}>
          <Text>
            Generated by DisputeDesk · {data.shopDomain} · Dispute {data.disputeId}
          </Text>
        </View>
      </Page>
    </Document>
  );
}
