/**
 * FinalDefenseStatementCard — Section 4 of ReviewSubmitTab.
 *
 * Renders the full bank-rebuttal text exactly as it will be sent.
 * The text itself is generated by lib/argument/* — this card only
 * labels and frames it.
 *
 * When `outdated === true` (the underlying pack changed after the
 * statement was generated), surfaces a Regenerate button that
 * delegates to the existing workspace action. The merchant decides
 * when to refresh; the card never auto-regenerates.
 *
 * Optional "Derived from:" sub-block surfaces the contributing
 * evidence categories (metadata, not weaknesses).
 */

"use client";

import {
  Card,
  BlockStack,
  InlineStack,
  Text,
  Banner,
  Button,
} from "@shopify/polaris";
import { useTranslations } from "next-intl";

const STATEMENT_TEXT_STYLE: React.CSSProperties = {
  fontFamily: "ui-monospace, SFMono-Regular, Menlo, monospace",
  fontSize: "13px",
  lineHeight: 1.6,
  whiteSpace: "pre-wrap",
  color: "#1a1a1a",
};

interface Props {
  text: string | null;
  derivedFrom: string[];
  outdated?: boolean;
  regenerating?: boolean;
  onRegenerate?: () => void;
}

export function FinalDefenseStatementCard({
  text,
  derivedFrom,
  outdated = false,
  regenerating = false,
  onRegenerate,
}: Props) {
  const t = useTranslations("disputes.reviewTab.sections.finalStatement");

  if (!text) return null;

  return (
    <Card>
      <BlockStack gap="300">
        <InlineStack align="space-between" blockAlign="center" gap="200">
          <Text as="h2" variant="headingMd">
            {t("title")}
          </Text>
          {outdated && onRegenerate ? (
            <Button
              size="slim"
              onClick={onRegenerate}
              loading={regenerating}
              disabled={regenerating}
            >
              {regenerating ? t("regenerating") : t("regenerate")}
            </Button>
          ) : null}
        </InlineStack>

        {outdated ? (
          <Banner tone="warning">
            <p>{t("outdated")}</p>
          </Banner>
        ) : null}

        <Text as="p" variant="bodySm" tone="subdued">
          {t("label")}
        </Text>
        <pre style={STATEMENT_TEXT_STYLE}>{text}</pre>
        {derivedFrom.length > 0 ? (
          <Text as="p" variant="bodySm" tone="subdued">
            <strong>{t("derivedFrom")}</strong> {derivedFrom.join(", ")}
          </Text>
        ) : null}
      </BlockStack>
    </Card>
  );
}
