-- 028: Add pt-BR (and de-DE, es-ES, sv-SE) translations for pack templates
-- Enables locale-aware template names/descriptions in PacksStep when user selects Portuguese, etc.

-- pt-BR
INSERT INTO pack_template_i18n (template_id, locale, name, short_description, works_best_for, preview_note) VALUES
('a0000000-0000-0000-0000-000000000001', 'pt-BR', 'Fraude / Não reconhecido — Padrão', 'Pacote de evidências completo para disputas de transações fraudulentas ou não reconhecidas. Cobre correspondência AVS, geolocalização IP, confirmação de entrega e histórico de interação com o cliente.', 'Chargebacks em que o titular do cartão afirma não ter autorizado a transação.', NULL),
('a0000000-0000-0000-0000-000000000002', 'pt-BR', 'Produto não recebido — Com rastreamento', 'Pacote de evidências forte para disputas PNR quando você tem rastreamento da transportadora mostrando entrega. Foca em prova de rastreamento, confirmação de entrega e cronograma de envio.', 'Disputas em que o cliente afirma não ter recebido, mas o rastreamento mostra entrega bem-sucedida.', NULL),
('a0000000-0000-0000-0000-000000000003', 'pt-BR', 'Produto não recebido — Sem rastreamento', 'Pacote de evidências para disputas PNR quando os dados de rastreamento não estão disponíveis. Baseia-se em recibos de envio, documentação de políticas e registros de interação com o cliente.', 'Disputas PNR com documentação de envio ausente ou limitada.', NULL),
('a0000000-0000-0000-0000-000000000004', 'pt-BR', 'Não conforme à descrição — Problemas de qualidade', 'Pacote de evidências para disputas alegando que o produto não corresponde à descrição ou tem defeitos. Foca em precisão da listagem, controle de qualidade e conformidade com a política de devolução.', 'Disputas em que os clientes alegam que o produto difere do anunciado.', NULL),
('a0000000-0000-0000-0000-000000000005', 'pt-BR', 'Assinatura cancelada — Abrangente', 'Pacote de evidências para disputas relacionadas a assinaturas. Cobre termos de assinatura, conformidade com política de cancelamento, logs de uso e histórico de notificações.', 'Disputas envolvendo cobranças recorrentes após o cliente alegar ter cancelado a assinatura.', NULL),
('a0000000-0000-0000-0000-000000000006', 'pt-BR', 'Reembolso/Crédito não processado — Padrão', 'Pacote de evidências para disputas alegando que reembolso ou crédito prometido não foi emitido. Foca em política de reembolso, registros de processamento e trilha de comunicação.', 'Disputas em que o cliente alega que o reembolso foi prometido mas não recebido.', NULL),
('a0000000-0000-0000-0000-000000000007', 'pt-BR', 'Duplicado / Valor incorreto', 'Pacote de evidências para disputas alegando cobrança duplicada ou valor incorreto. Foca em registros de transação, detalhamento do pedido e verificação de preços.', 'Disputas alegando cobrança dupla ou valor cobrado errado.', NULL),
('a0000000-0000-0000-0000-000000000008', 'pt-BR', 'Bens digitais / Serviço entregue', 'Pacote de evidências para disputas em produtos ou serviços digitais. Foca em logs de download/acesso, registros de uso e confirmação de entrega de conteúdo digital.', 'Disputas envolvendo downloads digitais, acesso SaaS ou serviços online.', NULL),
('a0000000-0000-0000-0000-000000000009', 'pt-BR', 'Políticas (Devoluções / Cancelamento / Envio)', 'Pacote de evidências centrado em políticas ideal quando sua melhor defesa são políticas claras e publicadas. Coleta políticas de devolução, cancelamento e envio com prova de aceitação do cliente.', 'Disputas em que as políticas do lojista apoiam claramente a cobrança e foram aceitas pelo cliente.', NULL),
('a0000000-0000-0000-0000-000000000010', 'pt-BR', 'Geral — Pacote flexível', 'Pacote de evidências flexível para tipos de disputa que não se encaixam em outras categorias. Cobre noções básicas do pedido, dados de envio disponíveis, políticas relevantes e comunicação com o cliente.', 'Qualquer tipo de disputa onde um modelo mais específico não está disponível.', NULL);

-- de-DE
INSERT INTO pack_template_i18n (template_id, locale, name, short_description, works_best_for, preview_note) VALUES
('a0000000-0000-0000-0000-000000000001', 'de-DE', 'Betrug / Nicht anerkannt — Standard', 'Umfassendes Beweispaket für betrügerische oder nicht anerkannte Transaktionen. Deckt AVS-Abgleich, IP-Geolokalisierung, Lieferbestätigung und Kundeninteraktionsverlauf ab.', 'Chargebacks, bei denen der Karteninhaber behauptet, die Transaktion nicht autorisiert zu haben.', NULL),
('a0000000-0000-0000-0000-000000000002', 'de-DE', 'Produkt nicht erhalten — Mit Tracking', 'Starkes Beweispaket für PNR-Streitfälle bei Sendungsverfolgung. Fokus auf Trackingnachweis, Lieferbestätigung und Versandzeitplan.', 'Streitfälle, in denen der Kunde Nichtzustellung behauptet, das Tracking aber erfolgreiche Lieferung zeigt.', NULL),
('a0000000-0000-0000-0000-000000000003', 'de-DE', 'Produkt nicht erhalten — Kein Tracking', 'Beweispaket für PNR-Streitfälle ohne oder mit unvollständigen Trackingdaten. Stützt sich auf Versandrechnungen, Richtliniendokumentation und Kundeninteraktionsaufzeichnungen.', 'PNR-Streitfälle mit fehlender oder begrenzter Versanddokumentation.', NULL),
('a0000000-0000-0000-0000-000000000004', 'de-DE', 'Nicht wie beschrieben — Qualitätsprobleme', 'Beweispaket für Streitfälle, die behaupten, das Produkt entspricht nicht der Beschreibung. Fokus auf Listungsgenauigkeit, Qualitätskontrolle und Rückgaberichtlinienkonformität.', 'Streitfälle, bei denen Kunden behaupten, das Produkt weicht von der Bewerbung ab.', NULL),
('a0000000-0000-0000-0000-000000000005', 'de-DE', 'Abonnement gekündigt — Umfassend', 'Beweispaket für abonnementbezogene Streitfälle. Deckt Abonnementbedingungen, Kündigungsrichtlinienkonformität, Nutzungsprotokolle und Benachrichtigungsverlauf ab.', 'Streitfälle mit wiederkehrenden Gebühren nach Kündigung durch den Kunden.', NULL),
('a0000000-0000-0000-0000-000000000006', 'de-DE', 'Rückerstattung nicht bearbeitet — Standard', 'Beweispaket für Streitfälle über nicht ausgezahlte Rückerstattungen. Fokus auf Rückerstattungsrichtlinie, Bearbeitungsnachweise und Kommunikationsverlauf.', 'Streitfälle, bei denen der Kunde behauptet, eine Rückerstattung wurde versprochen.', NULL),
('a0000000-0000-0000-0000-000000000007', 'de-DE', 'Doppelte / Falsche Belastung', 'Beweispaket für Streitfälle über doppelte Belastung oder falschen Betrag. Fokus auf Transaktionsnachweise, Bestellaufschlüsselung und Preisprüfung.', 'Streitfälle mit Doppelbelastung oder falschem Betrag.', NULL),
('a0000000-0000-0000-0000-000000000008', 'de-DE', 'Digitale Güter / Dienstleistung erbracht', 'Beweispaket für Streitfälle bei digitalen Produkten oder Dienstleistungen. Fokus auf Download-/Zugriffsprotokolle, Nutzungsnachweise und Lieferbestätigung.', 'Streitfälle zu digitalen Downloads, SaaS-Zugang oder Onlinediensten.', NULL),
('a0000000-0000-0000-0000-000000000009', 'de-DE', 'Richtlinien (Rückgabe / Kündigung / Versand)', 'Richtlinienzentriertes Beweispaket, ideal wenn Ihre stärkste Verteidigung klare, veröffentlichte Richtlinien sind.', 'Streitfälle, bei denen die Händlerrichtlinien die Belastung klar unterstützen.', NULL),
('a0000000-0000-0000-0000-000000000010', 'de-DE', 'Allgemein — Flexibles Paket', 'Flexibles Beweispaket für Streitfalltypen, die nicht in andere Kategorien passen. Deckt Bestellgrundlagen, Versanddaten, relevante Richtlinien und Kundenkommunikation ab.', 'Streitfälle ohne spezifischere Vorlage.', NULL);

-- es-ES
INSERT INTO pack_template_i18n (template_id, locale, name, short_description, works_best_for, preview_note) VALUES
('a0000000-0000-0000-0000-000000000001', 'es-ES', 'Fraude / No reconocido — Estándar', 'Paquete de evidencia completo para disputas de transacciones fraudulentas o no reconocidas. Cubre coincidencia AVS, geolocalización IP, confirmación de entrega e historial de interacción con el cliente.', 'Chargebacks donde el titular de la tarjeta afirma no haber autorizado la transacción.', NULL),
('a0000000-0000-0000-0000-000000000002', 'es-ES', 'Producto no recibido — Con seguimiento', 'Paquete de evidencia sólido para disputas PNR cuando tienes seguimiento del transportista mostrando entrega. Se centra en prueba de seguimiento, confirmación de entrega y cronograma de envío.', 'Disputas donde el cliente afirma no recepción pero el seguimiento muestra entrega exitosa.', NULL),
('a0000000-0000-0000-0000-000000000003', 'es-ES', 'Producto no recibido — Sin seguimiento', 'Paquete de evidencia para disputas PNR sin datos de seguimiento. Se basa en recibos de envío, documentación de políticas y registros de interacción con el cliente.', 'Disputas PNR con documentación de envío ausente o limitada.', NULL),
('a0000000-0000-0000-0000-000000000004', 'es-ES', 'No como se describe — Problemas de calidad', 'Paquete de evidencia para disputas que alegan que el producto no coincide con su descripción. Se centra en precisión del listado, control de calidad y cumplimiento de política de devoluciones.', 'Disputas donde los clientes alegan que el producto difiere del anunciado.', NULL),
('a0000000-0000-0000-0000-000000000005', 'es-ES', 'Suscripción cancelada — Completa', 'Paquete de evidencia para disputas relacionadas con suscripciones. Cubre términos de suscripción, cumplimiento de política de cancelación, registros de uso e historial de notificaciones.', 'Disputas con cargos recurrentes tras cancelación por parte del cliente.', NULL),
('a0000000-0000-0000-0000-000000000006', 'es-ES', 'Reembolso no procesado — Estándar', 'Paquete de evidencia para disputas que alegan reembolso o crédito prometido no emitido. Se centra en política de reembolso, registros de procesamiento y comunicación.', 'Disputas donde el cliente alega reembolso prometido pero no recibido.', NULL),
('a0000000-0000-0000-0000-000000000007', 'es-ES', 'Duplicado / Importe incorrecto', 'Paquete de evidencia para disputas que alegan cargo duplicado o importe incorrecto. Se centra en registros de transacciones, detalle del pedido y verificación de precios.', 'Disputas alegando doble cargo o importe incorrecto.', NULL),
('a0000000-0000-0000-0000-000000000008', 'es-ES', 'Bienes digitales / Servicio entregado', 'Paquete de evidencia para disputas en productos o servicios digitales. Se centra en registros de descarga/acceso, registros de uso y confirmación de entrega.', 'Disputas con descargas digitales, acceso SaaS o servicios en línea.', NULL),
('a0000000-0000-0000-0000-000000000009', 'es-ES', 'Políticas (Devoluciones / Cancelación / Envío)', 'Paquete de evidencia centrado en políticas ideal cuando tu mejor defensa son políticas claras publicadas. Recopila políticas con prueba de aceptación del cliente.', 'Disputas donde las políticas del comerciante apoyan claramente el cargo.', NULL),
('a0000000-0000-0000-0000-000000000010', 'es-ES', 'General — Paquete flexible', 'Paquete de evidencia flexible para tipos de disputa que no encajan en otras categorías. Cubre datos básicos del pedido, datos de envío, políticas relevantes y comunicación con el cliente.', 'Cualquier disputa sin plantilla más específica.', NULL);

-- sv-SE
INSERT INTO pack_template_i18n (template_id, locale, name, short_description, works_best_for, preview_note) VALUES
('a0000000-0000-0000-0000-000000000001', 'sv-SE', 'Bedrägeri / Icke erkänd — Standard', 'Omfattande bevispaket för bedrägliga eller icke erkända transaktioner. Täcker AVS-matchning, IP-geolokalisering, leveransbekräftelse och kundinteraktionshistorik.', 'Chargebacks där kortinnehavaren hävdar att de inte auktoriserade transaktionen.', NULL),
('a0000000-0000-0000-0000-000000000002', 'sv-SE', 'Produkt ej mottagen — Med spårning', 'Starkt bevispaket för PNR-tvister när du har transportörspårning som visar leverans. Fokuserar på spårningsbevis, leveransbekräftelse och frakttidslinje.', 'Tvister där kunden påstår icke-mottagande men spårningen visar lyckad leverans.', NULL),
('a0000000-0000-0000-0000-000000000003', 'sv-SE', 'Produkt ej mottagen — Utan spårning', 'Bevispaket för PNR-tvister utan tillgängliga spårningsdata. Förlitar sig på fraktkvitton, policydokumentation och kundinteraktionsregister.', 'PNR-tvister med saknad eller begränsad fraktdokumentation.', NULL),
('a0000000-0000-0000-0000-000000000004', 'sv-SE', 'Inte som beskrivet — Kvalitetsproblem', 'Bevispaket för tvister som påstår att produkten inte matchar beskrivningen. Fokuserar på listningsnoggrannhet, kvalitetskontroll och returpolicyefterlevnad.', 'Tvister där kunder påstår att produkten skiljer sig från reklamen.', NULL),
('a0000000-0000-0000-0000-000000000005', 'sv-SE', 'Prenumeration avslutad — Omfattande', 'Bevispaket för prenumerationsrelaterade tvister. Täcker prenumerationsvillkor, uppsägningspolicyefterlevnad, användningsloggar och notifikationshistorik.', 'Tvister med återkommande avgifter efter att kunden hävdar avslutad prenumeration.', NULL),
('a0000000-0000-0000-0000-000000000006', 'sv-SE', 'Återbetalning ej genomförd — Standard', 'Bevispaket för tvister om utlovad återbetalning som inte utförts. Fokuserar på återbetalningspolicy, processningsregister och kommunikationsspår.', 'Tvister där kunden hävdar att återbetalning utlovades men inte mottogs.', NULL),
('a0000000-0000-0000-0000-000000000007', 'sv-SE', 'Dubbel / Felaktig belopp', 'Bevispaket för tvister om dubbeldebitering eller felaktigt belopp. Fokuserar på transaktionsregister, orderuppdelning och prismatchningsverifiering.', 'Tvister om dubbel debitering eller felaktigt belopp.', NULL),
('a0000000-0000-0000-0000-000000000008', 'sv-SE', 'Digitala produkter / Tjänst levererad', 'Bevispaket för tvister om digitala produkter eller tjänster. Fokuserar på nedladdnings-/åtkomstloggar, användningsregister och leveransbekräftelse.', 'Tvister med digitala nedladdningar, SaaS-åtkomst eller onlinetjänster.', NULL),
('a0000000-0000-0000-0000-000000000009', 'sv-SE', 'Policys (Returer / Uppsägning / Frakt)', 'Policyorienterat bevispaket idealiskt när din starkaste försvar är tydliga, publicerade policys. Samlar retur-, uppsägnings- och fraktpolicys med kundacceptansbevis.', 'Tvister där handlarens policys stödjer debiteringen.', NULL),
('a0000000-0000-0000-0000-000000000010', 'sv-SE', 'Allmänt — Flexibelt paket', 'Flexibelt bevispaket för tvisttyper som inte passar in i andra kategorier. Täcker ordergrunderna, tillgängliga fraktdata, relevanta policys och kundkommunikation.', 'Tvister utan mer specifik mall.', NULL);
