-- PR-C1 — transactional lifecycle closure for defence-package promotion.
--
-- WHY A MIGRATION AT ALL. Every previous revision of this work implemented the
-- promotion contract as: a TypeScript preflight that proves the candidate is
-- current, content-safe and finalizable, followed by a SEPARATE PostgREST
-- update guarded on row fields. That is two round-trips, and the window
-- between them is real:
--
--   * a NEWER package version can be inserted after the preflight. The old row
--     is still `draft`, so the field-guarded update happily promotes a
--     candidate that is no longer current.
--   * the facts / narrative / PDF / validation the preflight inspected can be
--     rewritten before the promotion lands, so the row that gets filed is not
--     the row that was judged.
--   * the prior final can become `submitted` between "select the prior final"
--     and "mark it superseded", and the unguarded second update overwrites a
--     row the route explicitly promises never to touch.
--   * promotion + supersede + enqueue were three independent writes. A failed
--     enqueue left a final package, a superseded predecessor, and a "retriable"
--     result that could never actually retry — the retry refuses because the
--     package is no longer a draft, and reconciliation skips it because it only
--     looks at drafts.
--
-- None of that is fixable from the application side. This migration moves the
-- whole contract into two SECURITY DEFINER functions that run in one
-- transaction each.
--
-- WHAT STAYS IN TYPESCRIPT. Content safety. The claim detector and the
-- persisted-schema parser are NOT reproduced in SQL — they stay in
-- `lib/defence/packageSafety.ts`, which inspects the candidate and hands the
-- transaction the exact `content_revision` it inspected. The transaction's job
-- is to prove that nothing changed since, not to re-judge the content.

-- ─────────────────────────────────────────────────────────────────────────
-- 1. content_revision — a database-enforced revision of the inspected fields
-- ─────────────────────────────────────────────────────────────────────────
--
-- `updated_at` is NOT usable for this: it is maintained by a trigger that
-- fires on every update, so it changes for reasons unrelated to content (a
-- status flip, a superseded_by_id write) and would produce phantom conflicts —
-- and, more importantly, nothing forces a writer to move it in step with the
-- content. `content_revision` changes if and only if one of the four fields
-- the safety preflight reads changes, and it is the database that decides.

alter table defence_packages
  add column if not exists content_revision uuid not null default gen_random_uuid();

comment on column defence_packages.content_revision is
  'Database-enforced revision of the fields the PR-C1 safety preflight inspects '
  '(facts_json, narrative_json, pdf_path, validation_status). Regenerated by '
  'defence_packages_bump_content_revision on any change to those columns. '
  'Callers pass the value they inspected to finalize_defence_package / '
  'enqueue_defence_package_save so the transaction can refuse a candidate that '
  'was rewritten after inspection.';

create or replace function defence_packages_bump_content_revision()
returns trigger
language plpgsql
as $$
begin
  if new.facts_json is distinct from old.facts_json
     or new.narrative_json is distinct from old.narrative_json
     or new.pdf_path is distinct from old.pdf_path
     or new.validation_status is distinct from old.validation_status
  then
    new.content_revision := gen_random_uuid();
  end if;
  return new;
end;
$$;

drop trigger if exists defence_packages_content_revision on defence_packages;
create trigger defence_packages_content_revision
  before update on defence_packages
  for each row
  execute function defence_packages_bump_content_revision();

-- ─────────────────────────────────────────────────────────────────────────
-- 2. jobs.dedupe_key — idempotency under a lost RPC response
-- ─────────────────────────────────────────────────────────────────────────
--
-- A caller that never sees the reply cannot know whether the transaction
-- committed. It retries; the retry must not produce a second
-- `save_to_shopify` job, and must not report an unrecoverable lifecycle
-- failure for work that actually succeeded.

alter table jobs add column if not exists dedupe_key text;

create unique index if not exists jobs_dedupe_key_uniq
  on jobs (dedupe_key)
  where dedupe_key is not null;

comment on column jobs.dedupe_key is
  'Optional idempotency key. Unique when present. finalize_defence_package '
  'uses dpkg-finalize:<package_id> so a retried RPC cannot enqueue a duplicate '
  'save.';

-- ─────────────────────────────────────────────────────────────────────────
-- 3. finalize_defence_package — promote + supersede + enqueue, atomically
-- ─────────────────────────────────────────────────────────────────────────

create or replace function finalize_defence_package(
  p_package_id uuid,
  p_expected_revision uuid,
  p_expected_version integer,
  p_enqueue_save boolean default false
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_dispute_id uuid;
  v_pkg defence_packages%rowtype;
  v_latest_id uuid;
  v_prior_id uuid;
  v_prior_version integer;
  v_job_id uuid;
  v_dedupe text;
begin
  select dispute_id into v_dispute_id from defence_packages where id = p_package_id;
  if v_dispute_id is null then
    return jsonb_build_object('outcome', 'conflict', 'reason', 'missing_candidate');
  end if;

  -- ── The namespace lock ───────────────────────────────────────────────
  --
  -- `for update` on the parent dispute is what makes "is this still the
  -- latest version?" hold until COMMIT. It coordinates with EVERY existing
  -- candidate-creation path without those paths knowing about it: inserting a
  -- `defence_packages` row takes a FOR KEY SHARE lock on the referenced
  -- `disputes` row through `defence_packages_dispute_id_fkey`, and FOR KEY
  -- SHARE conflicts with FOR UPDATE. So a concurrent insert of a newer version
  -- blocks here rather than sneaking in behind the currency check. Proven
  -- against a real database in
  -- `scripts/db/finalizeDefencePackage.analysis.ts` (test 1), not asserted.
  perform 1 from disputes where id = v_dispute_id for update;

  select * into v_pkg from defence_packages where id = p_package_id;
  v_dedupe := 'dpkg-finalize:' || p_package_id::text;

  -- ── Idempotent replay ────────────────────────────────────────────────
  -- This exact revision is already promoted. Either we committed and lost the
  -- reply, or another caller did the identical work. Both are the same
  -- outcome, so converge on it: make sure the job exists and report success
  -- rather than a lifecycle failure.
  if v_pkg.status in ('final', 'submitted')
     and v_pkg.content_revision = p_expected_revision
  then
    if p_enqueue_save and v_pkg.status = 'final' then
      insert into jobs (shop_id, job_type, entity_id, dedupe_key)
      values (v_pkg.shop_id, 'save_to_shopify', v_pkg.source_pack_id::text, v_dedupe)
      on conflict (dedupe_key) where dedupe_key is not null do nothing
      returning id into v_job_id;
    end if;
    return jsonb_build_object(
      'outcome', 'already_done',
      'reason', 'already_promoted',
      'package_id', p_package_id,
      'version', v_pkg.version,
      'status', v_pkg.status,
      'job_id', v_job_id,
      'enqueued', v_job_id is not null
    );
  end if;

  -- ── The inspected candidate, unchanged ───────────────────────────────
  if v_pkg.content_revision is distinct from p_expected_revision then
    return jsonb_build_object('outcome', 'conflict', 'reason', 'content_changed');
  end if;
  if v_pkg.version is distinct from p_expected_version then
    return jsonb_build_object('outcome', 'conflict', 'reason', 'version_mismatch');
  end if;

  -- ── Lifecycle preconditions ──────────────────────────────────────────
  if v_pkg.status <> 'draft' then
    return jsonb_build_object('outcome', 'conflict', 'reason', 'not_draft', 'status', v_pkg.status);
  end if;
  if coalesce(v_pkg.validation_status, '') <> 'ok' then
    return jsonb_build_object('outcome', 'conflict', 'reason', 'validation_not_ok');
  end if;
  -- btrim, not `is not null`: the TypeScript contract requires
  -- `trim().length > 0`, and `.not("pdf_path","is",null)` accepted "" and "   ".
  if v_pkg.pdf_path is null or btrim(v_pkg.pdf_path) = '' then
    return jsonb_build_object('outcome', 'conflict', 'reason', 'missing_pdf');
  end if;

  -- ── Currency, inside the lock ────────────────────────────────────────
  select id into v_latest_id
    from defence_packages
   where dispute_id = v_dispute_id
   order by version desc
   limit 1;
  if v_latest_id is distinct from p_package_id then
    return jsonb_build_object('outcome', 'conflict', 'reason', 'not_current');
  end if;

  -- ── Promote ──────────────────────────────────────────────────────────
  update defence_packages
     set status = 'final', updated_at = now()
   where id = p_package_id
     and status = 'draft';
  if not found then
    return jsonb_build_object('outcome', 'conflict', 'reason', 'transition_lost');
  end if;

  -- ── Supersede the prior final, guarded on ITS expected state ─────────
  -- `submitted` rows are never touched: the guard is `status = 'final'` at
  -- write time, and the row lock means a concurrent worker flipping it to
  -- `submitted` either waits for us or wins and drops out of the predicate.
  select id, version into v_prior_id, v_prior_version
    from defence_packages
   where dispute_id = v_dispute_id
     and id <> p_package_id
     and status = 'final'
   order by version desc
   limit 1
   for update;

  if v_prior_id is not null then
    update defence_packages
       set status = 'superseded',
           superseded_by_id = p_package_id,
           updated_at = now()
     where id = v_prior_id
       and status = 'final';
    if not found then
      v_prior_id := null;
      v_prior_version := null;
    end if;
  end if;

  -- ── Enqueue, in the SAME transaction ─────────────────────────────────
  -- If this fails, the promotion and the supersede roll back with it, so the
  -- caller is left with a draft it can genuinely rebuild and retry.
  if p_enqueue_save then
    insert into jobs (shop_id, job_type, entity_id, dedupe_key)
    values (v_pkg.shop_id, 'save_to_shopify', v_pkg.source_pack_id::text, v_dedupe)
    on conflict (dedupe_key) where dedupe_key is not null do nothing
    returning id into v_job_id;
  end if;

  return jsonb_build_object(
    'outcome', 'promoted',
    'package_id', p_package_id,
    'version', v_pkg.version,
    'superseded_id', v_prior_id,
    'superseded_version', v_prior_version,
    'job_id', v_job_id,
    'enqueued', v_job_id is not null
  );
end;
$$;

comment on function finalize_defence_package(uuid, uuid, integer, boolean) is
  'PR-C1: promote an inspected draft to final, supersede the prior final and '
  '(optionally) enqueue the save — all in one transaction, under a FOR UPDATE '
  'lock on the parent dispute. Returns {outcome: promoted|already_done|conflict}.';

-- ─────────────────────────────────────────────────────────────────────────
-- 4. enqueue_defence_package_save — the direct Submit path
-- ─────────────────────────────────────────────────────────────────────────
--
-- Same currency + fileability contract, no promotion. Idempotent on an
-- in-flight save rather than on a permanent key, because a merchant may
-- legitimately re-save the same version after an earlier job finished.

create or replace function enqueue_defence_package_save(
  p_package_id uuid,
  p_expected_revision uuid
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_dispute_id uuid;
  v_pkg defence_packages%rowtype;
  v_latest_id uuid;
  v_job_id uuid;
begin
  select dispute_id into v_dispute_id from defence_packages where id = p_package_id;
  if v_dispute_id is null then
    return jsonb_build_object('outcome', 'conflict', 'reason', 'missing_candidate');
  end if;

  perform 1 from disputes where id = v_dispute_id for update;

  select * into v_pkg from defence_packages where id = p_package_id;

  if v_pkg.content_revision is distinct from p_expected_revision then
    return jsonb_build_object('outcome', 'conflict', 'reason', 'content_changed');
  end if;
  if v_pkg.status <> 'final' then
    return jsonb_build_object('outcome', 'conflict', 'reason', 'not_final', 'status', v_pkg.status);
  end if;
  if coalesce(v_pkg.validation_status, '') <> 'ok' then
    return jsonb_build_object('outcome', 'conflict', 'reason', 'validation_not_ok');
  end if;
  if v_pkg.pdf_path is null or btrim(v_pkg.pdf_path) = '' then
    return jsonb_build_object('outcome', 'conflict', 'reason', 'missing_pdf');
  end if;

  select id into v_latest_id
    from defence_packages
   where dispute_id = v_dispute_id
   order by version desc
   limit 1;
  if v_latest_id is distinct from p_package_id then
    return jsonb_build_object('outcome', 'conflict', 'reason', 'not_current');
  end if;

  -- An in-flight save for this pack already covers this request.
  select id into v_job_id
    from jobs
   where job_type = 'save_to_shopify'
     and entity_id = v_pkg.source_pack_id::text
     and status in ('queued', 'running', 'pending')
   limit 1;
  if v_job_id is not null then
    return jsonb_build_object('outcome', 'already_done', 'reason', 'save_already_queued', 'job_id', v_job_id);
  end if;

  insert into jobs (shop_id, job_type, entity_id)
  values (v_pkg.shop_id, 'save_to_shopify', v_pkg.source_pack_id::text)
  returning id into v_job_id;

  return jsonb_build_object('outcome', 'enqueued', 'job_id', v_job_id, 'package_id', p_package_id);
end;
$$;

comment on function enqueue_defence_package_save(uuid, uuid) is
  'PR-C1: enqueue save_to_shopify for an inspected, current, fileable final '
  'package — currency, fileability and the insert in one transaction.';

-- Server-only. Both functions bypass RLS by design and must never be callable
-- from a browser session.
revoke execute on function finalize_defence_package(uuid, uuid, integer, boolean) from public, anon, authenticated;
revoke execute on function enqueue_defence_package_save(uuid, uuid) from public, anon, authenticated;
grant execute on function finalize_defence_package(uuid, uuid, integer, boolean) to service_role;
grant execute on function enqueue_defence_package_save(uuid, uuid) to service_role;
