export interface HelpArticle {
  slug: string;
  category: string;
  titleKey: string;
  bodyKey: string;
  relatedSlugs?: string[];
  tags?: string[];
}

export const HELP_ARTICLES: HelpArticle[] = [
  // --- Getting Started ---
  {
    slug: "connect-shopify-store",
    category: "getting-started",
    titleKey: "help.articles.connectShopifyStore.title",
    bodyKey: "help.articles.connectShopifyStore.body",
    relatedSlugs: ["shopify-app-store-install", "first-dispute-sync", "understanding-dashboard"],
    tags: ["connect", "install", "shopify", "oauth", "setup", "reconnect", "permissions", "reauthorize"],
  },
  {
    slug: "shopify-app-store-install",
    category: "getting-started",
    titleKey: "help.articles.shopifyAppStoreInstall.title",
    bodyKey: "help.articles.shopifyAppStoreInstall.body",
    relatedSlugs: ["connect-shopify-store", "first-dispute-sync"],
    tags: ["app store", "install", "shopify", "add app", "oauth"],
  },
  {
    slug: "understanding-dashboard",
    category: "getting-started",
    titleKey: "help.articles.understandingDashboard.title",
    bodyKey: "help.articles.understandingDashboard.body",
    relatedSlugs: ["connect-shopify-store", "automation-overview"],
    tags: ["dashboard", "overview", "metrics", "kpi"],
  },
  {
    slug: "first-dispute-sync",
    category: "getting-started",
    titleKey: "help.articles.firstDisputeSync.title",
    bodyKey: "help.articles.firstDisputeSync.body",
    relatedSlugs: ["syncing-disputes", "connect-shopify-store"],
    tags: ["sync", "first", "import", "disputes"],
  },
  {
    slug: "automation-overview",
    category: "getting-started",
    titleKey: "help.articles.automationOverview.title",
    bodyKey: "help.articles.automationOverview.body",
    relatedSlugs: ["configuring-automation", "creating-first-rule"],
    tags: ["automation", "auto-build", "auto-save", "pipeline"],
  },

  // --- Disputes ---
  {
    slug: "viewing-filtering-disputes",
    category: "disputes",
    titleKey: "help.articles.viewingFilteringDisputes.title",
    bodyKey: "help.articles.viewingFilteringDisputes.body",
    relatedSlugs: ["dispute-detail-page", "review-queue", "syncing-disputes"],
    tags: ["view", "filter", "list", "status", "search"],
  },
  {
    slug: "dispute-detail-page",
    category: "disputes",
    titleKey: "help.articles.disputeDetailPage.title",
    bodyKey: "help.articles.disputeDetailPage.body",
    relatedSlugs: [
      "viewing-filtering-disputes",
      "generating-pack-manually",
      "uploading-evidence",
      "after-saving",
    ],
    tags: ["detail", "dispute", "stepper", "timeline", "supplemental", "kpi"],
  },
  {
    slug: "syncing-disputes",
    category: "disputes",
    titleKey: "help.articles.syncingDisputes.title",
    bodyKey: "help.articles.syncingDisputes.body",
    relatedSlugs: ["first-dispute-sync", "viewing-filtering-disputes"],
    tags: ["sync", "refresh", "webhook", "cron"],
  },
  {
    slug: "review-queue",
    category: "disputes",
    titleKey: "help.articles.reviewQueue.title",
    bodyKey: "help.articles.reviewQueue.body",
    relatedSlugs: ["approving-disputes", "creating-first-rule"],
    tags: ["review", "queue", "manual", "approval"],
  },
  {
    slug: "approving-disputes",
    category: "disputes",
    titleKey: "help.articles.approvingDisputes.title",
    bodyKey: "help.articles.approvingDisputes.body",
    relatedSlugs: ["review-queue", "how-packs-built"],
    tags: ["approve", "review", "override", "manual"],
  },

  // --- Evidence Packs ---
  {
    slug: "how-packs-built",
    category: "evidence-packs",
    titleKey: "help.articles.howPacksBuilt.title",
    bodyKey: "help.articles.howPacksBuilt.body",
    relatedSlugs: ["generating-pack-manually", "completeness-score"],
    tags: ["automatic", "build", "pipeline", "evidence", "order", "tracking"],
  },
  {
    slug: "generating-pack-manually",
    category: "evidence-packs",
    titleKey: "help.articles.generatingPackManually.title",
    bodyKey: "help.articles.generatingPackManually.body",
    relatedSlugs: ["how-packs-built", "uploading-evidence"],
    tags: ["manual", "generate", "create", "button"],
  },
  {
    slug: "completeness-score",
    category: "evidence-packs",
    titleKey: "help.articles.completenessScore.title",
    bodyKey: "help.articles.completenessScore.body",
    relatedSlugs: ["fixing-blockers", "evidence-checklist"],
    tags: ["score", "completeness", "percentage", "threshold"],
  },
  {
    slug: "fixing-blockers",
    category: "evidence-packs",
    titleKey: "help.articles.fixingBlockers.title",
    bodyKey: "help.articles.fixingBlockers.body",
    relatedSlugs: ["completeness-score", "uploading-evidence"],
    tags: ["blocker", "required", "missing", "fix"],
  },
  {
    slug: "uploading-evidence",
    category: "evidence-packs",
    titleKey: "help.articles.uploadingEvidence.title",
    bodyKey: "help.articles.uploadingEvidence.body",
    relatedSlugs: ["fixing-blockers", "evidence-checklist"],
    tags: ["upload", "file", "image", "pdf", "drag", "drop"],
  },
  {
    slug: "evidence-checklist",
    category: "evidence-packs",
    titleKey: "help.articles.evidenceChecklist.title",
    bodyKey: "help.articles.evidenceChecklist.body",
    relatedSlugs: ["completeness-score", "how-packs-built", "evidence-strength-rubric"],
    tags: ["checklist", "required", "recommended", "items"],
  },
  {
    slug: "evidence-strength-rubric",
    category: "evidence-packs",
    titleKey: "help.articles.evidenceStrengthRubric.title",
    bodyKey: "help.articles.evidenceStrengthRubric.body",
    relatedSlugs: ["evidence-checklist", "completeness-score", "how-packs-built", "fraud-risk-screening"],
    tags: ["strong", "moderate", "supporting", "invalid", "rubric", "categorization", "AVS", "CVV", "delivery", "policy"],
  },
  {
    slug: "returned-to-sender-parcels",
    category: "evidence-packs",
    titleKey: "help.articles.returnedToSenderParcels.title",
    bodyKey: "help.articles.returnedToSenderParcels.body",
    relatedSlugs: ["evidence-strength-rubric", "evidence-checklist", "uploading-evidence", "defense-letter-rebuttal"],
    tags: ["returned to sender", "RTS", "undelivered", "refused", "uncollected", "carrier", "delivery", "refund", "Klarna"],
  },
  {
    slug: "fraud-risk-screening",
    category: "evidence-packs",
    titleKey: "help.articles.fraudRiskScreening.title",
    bodyKey: "help.articles.fraudRiskScreening.body",
    relatedSlugs: ["evidence-strength-rubric", "evidence-checklist", "defense-letter-rebuttal"],
    tags: [
      "fraud screening",
      "pre-authorization",
      "shopify risk",
      "risk assessment",
      "AVS",
      "CVV",
      "IP",
      "billing",
      "shipping",
      "kept internal",
      "ACCEPT",
      "CANCEL",
      "REJECT",
      "INVESTIGATE",
    ],
  },
  {
    slug: "defense-letter-rebuttal",
    category: "evidence-packs",
    titleKey: "help.articles.defenseLetterRebuttal.title",
    bodyKey: "help.articles.defenseLetterRebuttal.body",
    relatedSlugs: ["evidence-checklist", "how-evidence-saved", "field-mapping"],
    tags: ["rebuttal", "defense letter", "issuer", "chargeback", "AVS", "CVV", "narrative"],
  },
  {
    slug: "evidence-pack-templates",
    category: "evidence-packs",
    titleKey: "help.articles.evidencePackTemplates.title",
    bodyKey: "help.articles.evidencePackTemplates.body",
    relatedSlugs: ["how-packs-built", "generating-pack-manually", "template-setup-wizard"],
    tags: [
      "template",
      "library",
      "install",
      "packs",
      "recommended",
      "auto-pack fraudulent disputes",
      "route not received to review queue",
      "auto-pack all disputes",
      "first matching rule wins",
      "you can change this later",
    ],
  },
  {
    slug: "template-setup-wizard",
    category: "evidence-packs",
    titleKey: "help.articles.templateSetupWizard.title",
    bodyKey: "help.articles.templateSetupWizard.body",
    relatedSlugs: ["evidence-pack-templates", "how-packs-built"],
    tags: ["template", "wizard", "setup", "customize", "evidence", "activate"],
  },
  {
    slug: "pack-variables",
    category: "evidence-packs",
    titleKey: "help.articles.packVariables.title",
    bodyKey: "help.articles.packVariables.body",
    relatedSlugs: ["how-packs-built", "evidence-checklist", "policy-variables"],
    tags: ["variables", "placeholders", "template", "order", "customer", "tracking", "dynamic"],
  },
  {
    slug: "pack-best-practices",
    category: "evidence-packs",
    titleKey: "help.articles.packBestPractices.title",
    bodyKey: "help.articles.packBestPractices.body",
    relatedSlugs: ["evidence-strength-rubric", "defense-letter-rebuttal", "evidence-checklist"],
    tags: ["best practices", "win rate", "tracking", "delivery", "policy", "narrative", "AVS"],
  },

  // --- Automation & Rules ---
  {
    slug: "configuring-automation",
    category: "automation-rules",
    titleKey: "help.articles.configuringAutomation.title",
    bodyKey: "help.articles.configuringAutomation.body",
    relatedSlugs: ["automation-overview", "completeness-blocker-gates"],
    tags: ["settings", "auto-build", "auto-save", "toggle", "configure"],
  },
  {
    slug: "creating-first-rule",
    category: "automation-rules",
    titleKey: "help.articles.creatingFirstRule.title",
    bodyKey: "help.articles.creatingFirstRule.body",
    relatedSlugs: ["rule-priority", "review-queue"],
    tags: ["rule", "create", "match", "action", "auto-pack"],
  },
  {
    slug: "rule-priority",
    category: "automation-rules",
    titleKey: "help.articles.rulePriority.title",
    bodyKey: "help.articles.rulePriority.body",
    relatedSlugs: ["creating-first-rule", "configuring-automation"],
    tags: ["priority", "order", "first", "match", "evaluation"],
  },
  {
    slug: "completeness-blocker-gates",
    category: "automation-rules",
    titleKey: "help.articles.completenessBlockerGates.title",
    bodyKey: "help.articles.completenessBlockerGates.body",
    relatedSlugs: ["configuring-automation", "completeness-score"],
    tags: ["gate", "threshold", "blocker", "completeness", "auto-save"],
  },
  {
    slug: "rule-presets",
    category: "automation-rules",
    titleKey: "help.articles.rulePresets.title",
    bodyKey: "help.articles.rulePresets.body",
    relatedSlugs: ["creating-first-rule", "configuring-automation"],
    tags: ["preset", "suggested", "install", "auto-pack", "review"],
  },

  // --- Policies ---
  {
    slug: "defining-store-policies",
    category: "policies",
    titleKey: "help.articles.definingStorePolicies.title",
    bodyKey: "help.articles.definingStorePolicies.body",
    relatedSlugs: ["policy-types-explained", "policy-variables", "policy-best-practices"],
    tags: [
      "policies",
      "terms",
      "refund",
      "shipping",
      "upload",
      "template",
      "preview template",
      "required",
      "optional",
      "link url",
      "upload file",
      "txt upload",
      "markdown upload",
    ],
  },
  {
    slug: "policy-types-explained",
    category: "policies",
    titleKey: "help.articles.policyTypesExplained.title",
    bodyKey: "help.articles.policyTypesExplained.body",
    relatedSlugs: ["defining-store-policies", "policy-variables", "policy-best-practices"],
    tags: ["shipping policy", "refund policy", "terms of service", "privacy policy", "policy types"],
  },
  {
    slug: "policy-variables",
    category: "policies",
    titleKey: "help.articles.policyVariables.title",
    bodyKey: "help.articles.policyVariables.body",
    relatedSlugs: ["defining-store-policies", "pack-variables", "policy-best-practices"],
    tags: ["variables", "placeholders", "policy", "template", "rebuttal", "narrative"],
  },
  {
    slug: "policy-best-practices",
    category: "policies",
    titleKey: "help.articles.policyBestPractices.title",
    bodyKey: "help.articles.policyBestPractices.body",
    relatedSlugs: ["defining-store-policies", "policy-types-explained", "policy-variables"],
    tags: ["best practices", "policy", "shipping", "refund", "terms", "checkout", "timestamp"],
  },

  // --- Billing & Plans ---
  {
    slug: "plan-comparison",
    category: "billing",
    titleKey: "help.articles.planComparison.title",
    bodyKey: "help.articles.planComparison.body",
    relatedSlugs: ["upgrading-plan", "pack-limits"],
    tags: ["plan", "free", "starter", "pro", "compare", "features"],
  },
  {
    slug: "upgrading-plan",
    category: "billing",
    titleKey: "help.articles.upgradingPlan.title",
    bodyKey: "help.articles.upgradingPlan.body",
    relatedSlugs: ["plan-comparison", "trial-period"],
    tags: ["upgrade", "billing", "payment", "shopify"],
  },
  {
    slug: "pack-limits",
    category: "billing",
    titleKey: "help.articles.packLimits.title",
    bodyKey: "help.articles.packLimits.body",
    relatedSlugs: ["plan-comparison", "upgrading-plan"],
    tags: ["limit", "quota", "monthly", "usage", "packs"],
  },
  {
    slug: "trial-period",
    category: "billing",
    titleKey: "help.articles.trialPeriod.title",
    bodyKey: "help.articles.trialPeriod.body",
    relatedSlugs: ["upgrading-plan", "plan-comparison"],
    tags: ["trial", "free", "7 days", "test"],
  },
  {
    slug: "store-session-upgrade",
    category: "billing",
    titleKey: "help.articles.storeSessionUpgrade.title",
    bodyKey: "help.articles.storeSessionUpgrade.body",
    relatedSlugs: ["upgrading-plan", "connect-shopify-store"],
    tags: ["upgrade", "billing", "reconnect", "store session", "shopify admin"],
  },

  // --- Saving to Shopify ---
  {
    slug: "how-evidence-saved",
    category: "saving-to-shopify",
    titleKey: "help.articles.howEvidenceSaved.title",
    bodyKey: "help.articles.howEvidenceSaved.body",
    relatedSlugs: ["field-mapping", "after-saving"],
    tags: ["save", "shopify", "api", "evidence", "fields"],
  },
  {
    slug: "field-mapping",
    category: "saving-to-shopify",
    titleKey: "help.articles.fieldMapping.title",
    bodyKey: "help.articles.fieldMapping.body",
    relatedSlugs: ["how-evidence-saved", "evidence-checklist"],
    tags: ["field", "mapping", "sections", "shopify", "evidence"],
  },
  {
    slug: "after-saving",
    category: "saving-to-shopify",
    titleKey: "help.articles.afterSaving.title",
    bodyKey: "help.articles.afterSaving.body",
    relatedSlugs: ["how-evidence-saved", "not-submit-to-networks"],
    tags: ["after", "saved", "next", "shopify admin", "review"],
  },
  {
    slug: "not-submit-to-networks",
    category: "saving-to-shopify",
    titleKey: "help.articles.notSubmitToNetworks.title",
    bodyKey: "help.articles.notSubmitToNetworks.body",
    relatedSlugs: ["how-evidence-saved", "after-saving"],
    tags: ["submit", "card network", "visa", "mastercard", "compliance"],
  },
  // --- Lifecycle ---
  {
    slug: "understanding-inquiries",
    category: "lifecycle",
    titleKey: "help.articles.understandingInquiries.title",
    bodyKey: "help.articles.understandingInquiries.body",
    relatedSlugs: ["understanding-chargebacks", "dispute-detail-page"],
    tags: ["inquiry", "pre-chargeback", "lifecycle", "phase", "early response"],
  },
  {
    slug: "understanding-chargebacks",
    category: "lifecycle",
    titleKey: "help.articles.understandingChargebacks.title",
    bodyKey: "help.articles.understandingChargebacks.body",
    relatedSlugs: ["understanding-inquiries", "dispute-detail-page", "how-packs-built"],
    tags: ["chargeback", "formal dispute", "evidence", "lifecycle", "phase"],
  },
  {
    slug: "lifecycle-overview",
    category: "lifecycle",
    titleKey: "help.articles.lifecycleOverview.title",
    bodyKey: "help.articles.lifecycleOverview.body",
    relatedSlugs: ["understanding-inquiries", "understanding-chargebacks", "configuring-automation"],
    tags: ["lifecycle", "inquiry", "chargeback", "phase", "coverage", "automation"],
  },

  // --- Liability Shift (LSE track: CE 3.0 + FPT + reason codes + ratios + session capture) ---
  {
    slug: "ce30-overview",
    category: "liability-shift",
    titleKey: "help.articles.ce30Overview.title",
    bodyKey: "help.articles.ce30Overview.body",
    relatedSlugs: [
      "auto-qualification-visa-secure",
      "subscription-ce30",
      "network-reason-codes",
      "vamp-ratio-explained",
    ],
    tags: ["ce 3.0", "visa", "liability shift", "compelling evidence", "10.4", "qualification"],
  },
  {
    slug: "auto-qualification-visa-secure",
    category: "liability-shift",
    titleKey: "help.articles.autoQualificationVisaSecure.title",
    bodyKey: "help.articles.autoQualificationVisaSecure.body",
    relatedSlugs: ["ce30-overview", "vamp-ratio-explained"],
    tags: ["visa secure", "3ds", "auto-qualified", "data only", "fee", "april 2026"],
  },
  {
    slug: "subscription-ce30",
    category: "liability-shift",
    titleKey: "help.articles.subscriptionCe30.title",
    bodyKey: "help.articles.subscriptionCe30.body",
    relatedSlugs: ["ce30-overview", "auto-qualification-visa-secure"],
    tags: ["subscription", "recurring", "mit", "initial billing", "ce 3.0"],
  },
  {
    slug: "mastercard-fpt",
    category: "liability-shift",
    titleKey: "help.articles.mastercardFpt.title",
    bodyKey: "help.articles.mastercardFpt.body",
    relatedSlugs: ["ce30-overview", "network-reason-codes", "session-capture"],
    tags: ["fpt", "mastercard", "first-party trust", "4837", "4863", "device delivery identity"],
  },
  {
    slug: "network-reason-codes",
    category: "liability-shift",
    titleKey: "help.articles.networkReasonCodes.title",
    bodyKey: "help.articles.networkReasonCodes.body",
    relatedSlugs: ["ce30-overview", "mastercard-fpt"],
    tags: ["reason code", "visa", "mastercard", "10.4", "4837", "rebuttal"],
  },
  {
    slug: "vamp-ratio-explained",
    category: "liability-shift",
    titleKey: "help.articles.vampRatioExplained.title",
    bodyKey: "help.articles.vampRatioExplained.body",
    relatedSlugs: ["ce30-overview", "mastercard-fpt", "auto-qualification-visa-secure"],
    tags: ["vamp", "ratio", "ecm", "efm", "threshold", "compliance", "fees"],
  },
  {
    slug: "session-capture",
    category: "liability-shift",
    titleKey: "help.articles.sessionCapture.title",
    bodyKey: "help.articles.sessionCapture.body",
    relatedSlugs: ["ce30-overview", "mastercard-fpt"],
    tags: ["session capture", "ip", "device", "privacy", "lgpd", "gdpr", "retention"],
  },
];

export function getArticleBySlug(slug: string): HelpArticle | undefined {
  return HELP_ARTICLES.find((a) => a.slug === slug);
}

export function getArticlesByCategory(category: string): HelpArticle[] {
  return HELP_ARTICLES.filter((a) => a.category === category);
}
