"use client";

import { X, FileText, Download } from "lucide-react";
import type { DemoDispute } from "@/lib/demo/fixtures/types";

interface DefensePackagePreviewProps {
  dispute: DemoDispute;
  onClose: () => void;
}

export function DefensePackagePreview({ dispute, onClose }: DefensePackagePreviewProps) {
  return (
    <div className="fixed inset-0 z-50 bg-[#0B1220]/60 backdrop-blur-sm flex items-center justify-center p-4" onClick={onClose}>
      <div
        className="bg-white rounded-xl shadow-2xl max-w-3xl w-full max-h-[90vh] flex flex-col"
        onClick={(e) => e.stopPropagation()}
      >
        <div className="flex items-center justify-between px-5 py-4 border-b border-[#E5E7EB]">
          <div className="flex items-center gap-2.5">
            <FileText className="w-5 h-5 text-[#7C3AED]" />
            <div>
              <h3 className="text-base font-semibold text-[#0B1220]">Defence package preview</h3>
              <p className="text-xs text-[#6B7280]">Dispute {dispute.id.toUpperCase()} · Order {dispute.orderName}</p>
            </div>
          </div>
          <div className="flex items-center gap-2">
            <button
              type="button"
              className="inline-flex items-center gap-1.5 h-8 px-3 text-xs rounded-md border border-[#E5E7EB] text-[#6B7280] hover:bg-[#F9FAFB] cursor-default"
              title="Demo only"
            >
              <Download className="w-3.5 h-3.5" />
              Download PDF
            </button>
            <button
              type="button"
              onClick={onClose}
              aria-label="Close preview"
              className="text-[#9CA3AF] hover:text-[#0B1220] transition-colors"
            >
              <X className="w-5 h-5" />
            </button>
          </div>
        </div>

        {/* PDF-shaped preview */}
        <div className="flex-1 overflow-y-auto bg-[#F1F2F4] p-6">
          <div className="bg-white shadow-md max-w-2xl mx-auto" style={{ aspectRatio: "8.5 / 11", minHeight: 800 }}>
            <div className="p-10">
              <div className="border-b-2 border-[#0B1220] pb-4 mb-6">
                <div className="text-xs uppercase tracking-wider text-[#6B7280]">Chargeback evidence package</div>
                <div className="text-2xl font-semibold text-[#0B1220] mt-1">Dispute response — Order {dispute.orderName}</div>
                <div className="flex gap-4 text-xs text-[#6B7280] mt-2">
                  <span>Dispute ID: {dispute.id.toUpperCase()}</span>
                  <span>·</span>
                  <span>Amount: ${dispute.amount.toFixed(2)} {dispute.currency}</span>
                  <span>·</span>
                  <span>Reason: {dispute.reasonLabel}</span>
                </div>
              </div>

              <div className="mb-6">
                <div className="text-xs font-semibold uppercase tracking-wider text-[#0B1220] mb-2">1. Bank rebuttal narrative</div>
                <p className="text-sm text-[#0B1220] leading-relaxed">{dispute.bankRebuttalNarrative}</p>
              </div>

              <div className="mb-6">
                <div className="text-xs font-semibold uppercase tracking-wider text-[#0B1220] mb-2">2. Supporting evidence</div>
                <ul className="space-y-1.5">
                  {dispute.evidence.map((e, idx) => (
                    <li key={e.id} className="text-sm text-[#0B1220]">
                      <span className="font-medium">{idx + 1}.</span> {e.label} — <span className="text-[#6B7280]">{e.detail}</span>
                    </li>
                  ))}
                </ul>
              </div>

              <div>
                <div className="text-xs font-semibold uppercase tracking-wider text-[#0B1220] mb-2">3. Evidence-to-Shopify field mapping</div>
                <table className="w-full text-xs">
                  <thead>
                    <tr className="border-b border-[#E5E7EB] text-[#6B7280]">
                      <th className="text-left py-1.5">Shopify field</th>
                      <th className="text-left py-1.5">Source</th>
                    </tr>
                  </thead>
                  <tbody>
                    {dispute.shopifyFieldMap.map((m, idx) => (
                      <tr key={idx} className="border-b border-[#F1F2F4]">
                        <td className="py-1.5 font-medium text-[#0B1220]">{m.slot}</td>
                        <td className="py-1.5 text-[#6B7280]">{m.sourceFields.join(", ")}</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>

              <div className="mt-8 pt-4 border-t border-[#E5E7EB] text-[10px] text-[#9CA3AF] text-center">
                Generated by DisputeDesk · {dispute.id.toUpperCase()} · Strength {dispute.strengthScore}%
              </div>
            </div>
          </div>
        </div>

        <div className="px-5 py-3 border-t border-[#E5E7EB] bg-[#F9FAFB] text-xs text-[#6B7280] text-center">
          Demo preview — in production this PDF is generated and saved directly to Shopify&apos;s evidence slots.
        </div>
      </div>
    </div>
  );
}
